# Generated by Django 2.2.24 on 2022-01-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='isAvailable',
        ),
    ]
